version: '0.2'

services:
  frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      ports:
        - "4200:4200"
      volumes:
        - ./frontend:/app
        - /app/node_modules
      restart: unless-stopped
    
  db:
    image: postgres:17
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/CreacionesNicole.sql:/docker-entrypoint-initdb.d/init.sql
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    depends_on:
      - db
  
volumes:
  postgres_data: